### ISSUE TITLE
Can the "fmm.stream3d" function in this program be used for ray tracing in complex, heterogeneous velocity models?

### ISSUE THREAD

**Issue by dulu1** [aaspip/pyekfmm#4]
Thanks for implementing and sharing these useful package.
Can the "fmm.stream3d" function in this program be used for ray tracing in complex, heterogeneous velocity models?
When I was conducting tests, I found that it seems to only be able to trace a portion of the path.
Is there any requirement on the velocity model or tracking points in order to trace the complete path?
Thanks!

dulu

**Comment by chenyk1990** [comment]
It should be able, but anisotropy is not enabled currently.

**Comment by dulu1** [comment]
Thanks for your reply.
When I was conducting tests, I found that it seems to only be able to trace a portion of the path.
Is there any requirement on the velocity model or tracking points in order to trace the complete path?

**Comment by chenyk1990** [comment]
No there are no such requirements or limitations. You can check the ray
tracing examples and mimic that by changing a new velocity model. Most
likely you do not use the function correctly.

**Comment by dulu1** [comment]
Thanks for your reply.
Your answer has been very helpful to me.

**Comment by dulu1** [comment]
After changing the receiver location from 101,101,101 to 51,61,101 in 'test_pyekfmm_fig4.py', there appeared missing parts in the ray tracing. from        ''paths,nrays=fmm.stream3d(-tx,-ty, -tz, 101, 101, ii, step=0.1, maxvert=10000)''    to     ''paths,nrays=fmm.stream3d(-tx,-ty, -tz, 51, 61, ii, step=0.1, maxvert=10000)''.If I use fmm.trimrays after that,The missing parts became a straight line.
`for ii in range(1,102,50):`
`    paths,nrays=fmm.stream3d(-tx,-ty, -tz, 61, 51, ii, step=0.1, maxvert=10000)`
`    plt.plot((51-1)*dy,(61-1)*dx,(ii-1)*dz,'vb',markersize=10);`
`    #paths=fmm.trimrays(paths,start_points=np.array([1,1,1]),T=0.5)`
`    plt.plot((paths[1,:]-1)*dy,(paths[0,:]-1)*dx,(paths[2,:]-1)*dz,'g--',markersize=20);`
![Screenshot 2023-10-10 233615](https://github.com/aaspip/pyekfmm/assets/141817945/2a661a4c-3b52-4d71-8dc8-226f03f99c1a)

**Comment by dulu1** [comment]
It will not have any missing parts when x=y.

**Comment by chenyk1990** [comment]
Interesting issue! Thank you for letting me know. I will look into it and
get back to you.

**Comment by chenyk1990** [comment]
Hi, you can update the pyekfmm package and run

test_pyekfmm_fig4.py again. In the current case, it works when x!=y.


Let me know if it works for you.

**Comment by dulu1** [comment]
I installed using pip, and perhaps pip hasn't been updated yet. However, after extracting the modified part of your source code and running it, I found that the issue has been resolved. Thank you for your help!
Thank you once again for your patience！

**Comment by dulu1** [comment]
What you initially mentioned, "anisotropy is not enabled currently" .Does this mean that there will be errors in the results of ray tracing if I use an anisotropic velocity model?

**Comment by chenyk1990** [comment]
Anisotropic ray tracing requires inputting anisotropic parameters,
basically you cannot input such parameters so you cannot make it work. If
only velocity is used, it is still isotopic ray tracing. Hope this helps!

**Comment by dulu1** [comment]
Thank you very much for your answer, all my questions have been resolved. Thank you again!

**Comment by chenyk1990** [comment]
You're welcome!
