### ISSUE TITLE
Velocity model does not plot correctly.

### ISSUE THREAD

**Issue by andresp-wave** [aaspip/pyekfmm#6]
First, thanks for developing this great tool ! 

I believe that the plot3d function does not work for all cases. If I'm not wrong, it always assumes that the spatial sampling is 0.01. 
"L52	X, Y, Z = np.meshgrid(np.arange(nx)*0.01, np.arange(ny)*0.01, np.arange(nz)*0.01)"
For example in "test_pyekfmm_raytrainc3d.py" when I change the spatial sampling to 0.1 the size of the velocity model should change to 30( in the depth axis) but it remains to the same value of 3 km.

**Comment by chenyk1990** [comment]
Hi, Andres,

Please try again. It should be fixed. Let me know if you have any problems.
The example is at
https://github.com/aaspip/pyekfmm/blob/main/demos/test_pyekfmm_raytracing3d.py

Best,
YC

**Comment by andresp-wave** [comment]
Hi Yangkang,

I just tested and it works. Thanks ! I'll let you know if I encounter any other issues using pyekfmm.

Best,
Andres
